FROM ubuntu:22.04

RUN apt-get update && apt-get install -y python3.10 python3-pip python3-venv \
    python-is-python3 cmake build-essential z3 m4 libgmp-dev 
COPY ./cvc5 /app/cvc5
WORKDIR /app/cvc5
RUN ./configure.sh --auto-download && mkdir -p build && cd ./build && make && make install
WORKDIR /app
RUN python -m venv venv && . venv/bin/activate && \
    pip install z3-solver numpy


# we could use dockerfile-plus to avoid duplicating the base image
# syntax = edrevo/dockerfile-plus
# INCLUDE+ Dockerfile.base
# for metalift
RUN apt install -y clang llvm apt-utils git wget software-properties-common && \
    add-apt-repository -y ppa:plt/racket && \
    apt-get install -y racket
COPY metalift/metalift /app/metalift
RUN raco pkg install --auto rosette && \
    . /app/venv/bin/activate && \
    pip install pyparsing llvmlite mypy regex && \
    cd /app/metalift && \
    pip install -e .